{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "87709187-75b0-4a86-a4d3-091116429778",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "2b050c09-a59c-43da-a832-e76628c0b9a4",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>TV</th>\n",
       "      <th>Radio</th>\n",
       "      <th>Newspaper</th>\n",
       "      <th>Sales</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>230.1</td>\n",
       "      <td>37.8</td>\n",
       "      <td>69.2</td>\n",
       "      <td>22.1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>44.5</td>\n",
       "      <td>39.3</td>\n",
       "      <td>45.1</td>\n",
       "      <td>10.4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>17.2</td>\n",
       "      <td>45.9</td>\n",
       "      <td>69.3</td>\n",
       "      <td>9.3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>151.5</td>\n",
       "      <td>41.3</td>\n",
       "      <td>58.5</td>\n",
       "      <td>18.5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>180.8</td>\n",
       "      <td>10.8</td>\n",
       "      <td>58.4</td>\n",
       "      <td>12.9</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "      TV  Radio  Newspaper  Sales\n",
       "0  230.1   37.8       69.2   22.1\n",
       "1   44.5   39.3       45.1   10.4\n",
       "2   17.2   45.9       69.3    9.3\n",
       "3  151.5   41.3       58.5   18.5\n",
       "4  180.8   10.8       58.4   12.9"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "df = pd.read_csv(r\"C:\\Users\\Lenovo\\OneDrive\\Desktop\\Sales prediction\\advertising.csv\")\n",
    "\n",
    "# Remove unwanted index column if present\n",
    "df = df.loc[:, ~df.columns.str.contains('^Unnamed')]\n",
    "\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "97b5884d-3efc-494f-89f0-e830a06fffb0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Index(['TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')\n"
     ]
    }
   ],
   "source": [
    "print(df.columns)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "43ab00cb-22e4-4334-93b6-ee101f723f56",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAjMAAAHFCAYAAAAHcXhbAAAAOnRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjEwLjYsIGh0dHBzOi8vbWF0cGxvdGxpYi5vcmcvq6yFwwAAAAlwSFlzAAAPYQAAD2EBqD+naQAAVkVJREFUeJzt3Xt0VNXZP/DvJCSTEJKBgDATgRC5iCEKUkVQFEqBgoAoagWlAuW1asFKbX/i5aWEUgVcrWILyCtFwFKItiL3RuENoCgRBSMgahGDICTyEiDBkARI9u+POGMmmTNzzsy57DPz/ayVtWQuZ/bsOc55Zu9nP9shhBAgIiIisqk4qxtAREREFAkGM0RERGRrDGaIiIjI1hjMEBERka0xmCEiIiJbYzBDREREtsZghoiIiGyNwQwRERHZGoMZIiIisjUGM0QxzuFwqPp78cUX4XA4kJ+fr3isJUuWwOFwYM2aNSa+A39CCOTl5eHmm29G27ZtkZSUhPbt2+OnP/0p/va3v4V1zIEDB2LgwIH6NpSIdOPgdgZEsa2wsNDv37Nnz8a2bdtQUFDgd7vH48GVV16J2267Da+//nrAY91444348ssvcfz4cSQkJBjW5mCeeOIJzJs3Dw888ABGjhyJ1NRUfP311ygoKMCZM2ewYcMGzcf0BjLbt2/Xt7FEpItmVjeAiKzVt29fv39fdtlliIuLa3I7AIwePRpr165FWVkZWrdu7Xff559/jl27duG3v/2tZYFMVVUV5s+fj/vvvx8vv/yy330TJ05EXV2dJe0iImNxmomIVJs8eTIuXLiAVatWNblv2bJlAIBf/OIXis+fP38+HA4Hvvzyyyb3TZ8+HYmJiTh16hQA4OOPP8bIkSPRtm1bOJ1OZGRkYMSIEfjmm28Uj19ZWYmamhp4PJ6A98fF+X/lzZo1CzfccAPS09ORlpaG3r17Y+nSpVAzYH3hwgX88Y9/RPfu3eF0OnHZZZdh0qRJ+L//+z+/xxUUFGDgwIFo3bo1kpOT0bFjR9x55504f/58yNcgInUYzBCRaoMHD0ZmZiZeeeUVv9tra2vx97//HX379kV2drbi88ePH4/ExEQsX768yfNXrlyJUaNGoU2bNqisrMSQIUPw7bffYuHChdiyZQvmz5+Pjh074ty5c4rHb9OmDbp06YJFixbh+eefx+effx40MDly5AgefPBBvP7661izZg3GjBmDRx55BLNnzw7aD3V1dRg9ejTmzp2Le++9F5s2bcLcuXOxZcsWDBw4EFVVVb7jjxgxAomJiXjllVeQn5+PuXPnIiUlBRcuXAj6GkSkgSAiamDChAkiJSVF8f6ZM2cKAGLv3r2+2zZs2CAAiCVLloQ8/pgxY0T79u1FbW2t77bNmzcLAGLDhg1CCCE++ugjAUCsXbtWc/t3794tOnbsKAAIACI1NVWMHDlSvPrqq6Kurk7xebW1teLixYviD3/4g2jdurXfYwcMGCAGDBjg+/fq1asFAPHGG2/4HePDDz8UAMSiRYuEEEL861//EgBEUVGR5vdBROpxZIaINJk0aRLi4uL8RmeWLVuGlJQU3HPPPaqe/80332Dr1q1+z3e73Rg+fDgAoEuXLmjVqhWmT5+OxYsX4+DBg6rbd/311+PLL79Efn4+nnrqKfTr1w//+7//i/vvvx+33Xab30hNQUEBBg8eDJfLhfj4eCQkJOD3v/89ysrKcPLkScXX2LhxI1q2bIlRo0bh0qVLvr9evXrB7Xb7EoV79eqFxMRE/PKXv8SKFSvw1VdfqX4fRKQegxki0iQzMxM/+clPsGrVKtTU1ODUqVPYuHEj7r77bqSmpoZ8/vDhw+HxeHw5NmfOnMH69etx//33Iz4+HgDgcrmwY8cO9OrVC0899RR69OiBjIwMzJw5ExcvXgz5GgkJCfjpT3+KZ555Bm+99RaOHTuGgQMHYuPGjfj3v/8NANi9ezeGDh0KoH5J+XvvvYcPP/wQTz/9NAD4pooC+fbbb3H27FkkJiYiISHB76+0tNSX99O5c2ds3boVbdu2xZQpU9C5c2d07twZL774Ysj3QETqcTUTEWk2efJkbNmyBevWrcOJEydw4cIFTJ48WdVz4+Pj8fOf/xx/+ctfcPbsWV9QNGnSJL/HXX311cjLy4MQAvv27cPy5cvxhz/8AcnJyXjiiSc0tbd169aYNm0atm/fjgMHDuDWW29FXl4eEhISsHHjRiQlJfkeu3bt2pDHa9OmDVq3bq1Yc6dhUHfzzTfj5ptvRm1tLT766CP89a9/xbRp09CuXTuMHTtW0/sgosA4MkNEmt1+++1o3bo1XnnlFSxbtgzdunVD//79VT9/0qRJqK6uxurVq7F8+XL069cP3bt3D/hYh8OBnj174oUXXkDLli2xd+9exeNevHgRZWVlAe/77LPPAAAZGRm+4zZr1sw3GgTUj8b8/e9/D9n+kSNHoqysDLW1tbjuuuua/F155ZVNnhMfH48bbrgBCxcuBICg74OItOHIDBFp5nQ6cd999+Gvf/0rhBCYO3eupud3794d/fr1w5w5c3Ds2LEmNWE2btyIRYsW4fbbb8cVV1wBIQTWrFmDs2fPYsiQIYrHLS8vR6dOnXD33Xdj8ODB6NChA7777jts374dL774Iq666iqMGTMGADBixAg8//zzuPfee/HLX/4SZWVl+NOf/gSn0xmy/WPHjsU//vEP3HrrrXj00UfRp08fJCQk4JtvvsG2bdswevRo3HHHHVi8eDEKCgowYsQIdOzYEdXV1b5co8GDB2vqMyIKwtr8YyKSTajVTF6ffPKJACDi4+PFiRMnNL/Oyy+/LACI5ORkUV5e7nff559/LsaNGyc6d+4skpOThcvlEn369BHLly8Pesyamhrxpz/9SQwfPlx07NhROJ1OkZSUJK666irx+OOPi7KyMr/Hv/LKK+LKK68UTqdTXHHFFWLOnDli6dKlAoAoLi72Pa7xaiYhhLh48aL405/+JHr27CmSkpJEixYtRPfu3cWDDz4oDh06JIQQYteuXeKOO+4QmZmZwul0itatW4sBAwaI9evXa+4vIlLG7QyIiIjI1pgzQ0RERLbGYIaIiIhsjcEMERER2RqDGSIiIrI1BjNERERkawxmiIiIyNaivmheXV0dTpw4gdTUVDgcDqubQ0RERCoIIXDu3DlkZGQgLi742EvUBzMnTpxAhw4drG4GERERheHYsWNo37590MdEfTDj3fDt2LFjSEtLs7g1REREpEZFRQU6dOjgt3GrkqgPZrxTS2lpaQxmiIiIbEZNiggTgImIiMjWGMwQERGRrTGYISIiIltjMENERES2xmCGiIiIbI3BDBEREdkagxkiIiKyNQYzREREZGsMZoiIiMjWor4CMBERUbSrrRPYXXwaJ89Vo21qEvpkpSM+LnY2V2YwQ0REZGP5B0owa8NBlJRX+27zuJIwc1Q2huV4LGyZeTjNREREZFP5B0rw8Mq9foEMAJSWV+PhlXuRf6DEopaZi8EMERGRDdXWCczacBAiwH3e22ZtOIjaukCPiC4MZoiIiGxod/HpJiMyDQkAJeXV2F182rxGWYTBDBERkQ2dPKccyITzODtjMENERGRDbVOTdH2cnTGYISIisqE+WenwuJKgtADbgfpVTX2y0s1sliUYzBAREdlQfJwDM0dlA0CTgMb775mjsmOi3gyDGSIiIpsaluPBS+N7w+3yn0pyu5Lw0vjeMVNnhkXziIiIbGxYjgdDst2sAExERET2FR/nQL/OrcN+vt23Q2AwQ0REFMOiYTsE5swQERHFqGjZDoHBDBERUQyKpu0QGMwQERHFoGjaDoHBDBERUQyKpu0QGMwQERHFoGjaDoHBDBERUQyKpu0QGMwQERHFoGjaDoHBDBERUYyorRPYdbgM64qOY9fhMgzJdkfFdggsmkdERDFHtoq3ZrQnWHG8ndMH+V6/TQsnIIBTlTXYdbjM8r5Rg8EMERHFFNkq3prRHm9xvMYVY7zF8byjMPkHSvC7f34iTd+oxWkmIiKKGbJVvDWjPWqL423ed0KqvtGCwQwREcUE2SremtUetcXx/nvdAWn6RisGM0REFBNkq3hrVnvUFr07XXnR8LYYhcEMERHFBNkq3prVHj2L3slaDdjSYGbOnDm4/vrrkZqairZt2+L222/HF1984feYiRMnwuFw+P317dvXohYTEZFdyVbx1qz2qCmO1zol0ZS2GMXSYGbHjh2YMmUKCgsLsWXLFly6dAlDhw5FZWWl3+OGDRuGkpIS39/mzZstajEREdmVbBVvzWqPmuJ4s0fnSNU3WlkazOTn52PixIno0aMHevbsiWXLluHo0aPYs2eP3+OcTifcbrfvLz1dzs4kIiJ5yVbx1sz2DMvxBC2Od+s1Hqn6Riup6syUl5cDQJNgZfv27Wjbti1atmyJAQMG4JlnnkHbtm0DHqOmpgY1NTW+f1dUVBjXYCIiUk2GQnXei3rjui5ui2qpmNmeYTkeDMl2K34GsvWNFg4hhBTrrIQQGD16NM6cOYN3333Xd/trr72GFi1aIDMzE8XFxZgxYwYuXbqEPXv2wOl0NjlObm4uZs2a1eT28vJypKWlGfoeiIgoMNkK1ckQWMnaHlnaUlFRAZfLper6LU0wM2XKFGzatAk7d+5E+/btFR9XUlKCzMxM5OXlYcyYMU3uDzQy06FDBwYzREQWUao+67082mkPIDKPlmBGimmmRx55BOvXr8c777wTNJABAI/Hg8zMTBw6dCjg/U6nM+CIDRERmS9UYTgH6ouxDcl2S5uPQfKzNAFYCIGpU6dizZo1KCgoQFZWVsjnlJWV4dixY/B4GMUTEclOtkJ1sajxTtmyVvGNhKUjM1OmTMGqVauwbt06pKamorS0FADgcrmQnJyM7777Drm5ubjzzjvh8Xhw5MgRPPXUU2jTpg3uuOMOK5tOREQqyFaoLtbIlqtkFEtHZl566SWUl5dj4MCB8Hg8vr/XXnsNABAfH4/9+/dj9OjR6NatGyZMmIBu3bph165dSE1NtbLpRESkgmyF6mKJbJtqGsnSkZlQucfJycl46623TGoNERHpzVsYrrS8OmDejAP1S39lLcamF7NXCMVarpIUCcBERBSdvIXhHl65Fw7A7+Jqh2JserBiqkdLrlK/zq0NaYOZuNEkEREZKlT12WjK3WjMqqmeWMtV4sgMEREZLlT12Whk5VRPrOUqMZghIiJTxMc5omJKQy0rp3piLVeJ00xERKRJLNQt0YOVUz1mbGIp03nAkRkiIlItVuqW6MHqqR4jN46U7TyQZm8mo2jZ24GIKJpFujyYeyxpU1sn0H9eQcipnp3TBxm+TFvPXCWzzgPb7c1ERETGivSXdKzVLdGDLMvS9cxVkvU8YM4MEVGU02N5MPdYCk+0LUuX9TzgyAwRURTT65d0rNUt0VM0LUuX9TxgMENEFMX0Wh5sdTKr3UXLsnRZzwNOMxERRTG9fkl765YojSU4UJ+DEy11SygwWc8DBjNERFFMr1/SZtQtMYpM9VDsTtbzgNNMRERRTM9KsEbWLTGKbPVQooGM5wHrzBARRTnvaiYg8PJgratq9K5bYhTWxTGW0eeBlus3gxkiohgQayMU3oJ1SsnPZhWso/CxaB4REfmJpuXBali5ySOZj8EMEVGMiJblwWrIWg+FjMHVTEREFHVkrYdCxmAwQ0REUUfWeihkDAYzRETko0dNFhnqushaD4WMwZwZIiICoM+KJ5lWTclYD4WMwaXZRESkS00WWeu62KUuDvnj0mwiohim9eKtx87aeu3ObYRYWsUVqxjMEBFFkXCmefSoycK6LmQlJgATEUUJ7zRP46CitLwaD6/ci/wDJQGfp0dNlmiv6yJDUjMp48gMEVEUiGSaR4+aLGqPceTUeVWPk4lMSc0UGEdmiIiigJZpnsb0qMnSJysd7jRnyHbmfXjUVsu9wx3tInMxmCEiigKRTPPoUZMlPs6BcX06hnx9pYAqmPwDJeg/rwDjlhTi0bwijFtSiP7zCgwPJEKNdgH1o12ccrIegxkioigQ6VSRtyaL2+V/v9uVpHpJdac2KaraoCVvxsqRkUhGu8hczJkhIooC3qmi0vLqgCMJDtQHJsGmiiLdWVvv/ZCsXu4d7UnN0YQjM0REUUCv8v3emiyje12Ofp1bawoS9N4PyYiRES25N9ys0j44MkNEFCWsKt/fsEjf2Os74IWth+AA/EZUwtkPSe+REa2rkvQY7SJzMJghIooikU4VaRUoQGjZPAEAcPb8Rd9t4QRUeo6MKG214M29CZQX5B3tenjlXl2CMzIOgxkioihjVvl+pQCh/Psg5jeDu6FTm+ZhB1R6jYxEknvDzSrtgcEMERFppiZAyPvwKHZOHxTRyIV32qoxLSMjkW61YPZoF2nHYIaIiDQzei+mQNNXDWkZGdEj9ybWN6uUfedxBjNERKSZkcuWlaavvH4zuBumDupi2ZLxWGOH7Ry4NJuIiDQzKkAINn0F/DB9pYXeS8ZjiV22c2AwQ0QkAbvtymxUgGBEbRm9avDEGjtt58BpJiIii9lhGL8xo5YtGzV9xVVJ2hmdF6UnBjNERBYKp/6JLIwIEIzMb+GqJG3stJ0DgxkiIotYvfeQHvQOEIyuuhvrq5K0sFPiNHNmiIgsEi27Mkeyn1OgYzG/RQ52SpxmMENEZBE7DeObyTt95Xb5/+J3u5KknnYzi1nJ4nYKLDnNRERkEbXD821SnAa3RD56TF/JXugtHGYniyvlRbVKScAfR+dIE1g6hBDWr6kyUEVFBVwuF8rLy5GWlmZ1c4iIfGrrBPrPK1DMD/FypyUh9zauuNHCjivEQlFKFveGZ0aOWm3eV4L/XncApysv+G4zuj+1XL85zUREZJFgw/gNfVshV4Ey2dml0JsWVtZ8yT9Qgimr9voFMoBc/clghojIQt5h/HZpylNJshUok5mdCr1pYVWyuF36k8EMEZHFhuV48Oef9Qr6GLusbLJatKwQa8yqZHG79CeDGSIiCZz6rkbV42JtZZNW0bpCzKqaL3bpTwYzREQSsFOBMplFaz9aVfPFLv3JYIaISAJ2KlAmM7360ahaLuEe16qaL3Y5L1lnhohIAkZt3Cgbo2u/6NGPRi3rjvS4VmyWaZfzknVmiIgkEo31UbzMfG/hvpZRtVz0PK4VxQCtOC+1XL8tDWbmzJmDNWvW4PPPP0dycjJuvPFGzJs3D1deeaXvMUIIzJo1Cy+//DLOnDmDG264AQsXLkSPHj1UvQaDGSKym2itXGt2wTet/egtYqi0ese7yeXO6YM0VyI24rhmM/u8tE3RvB07dmDKlCkoLCzEli1bcOnSJQwdOhSVlZW+xzz33HN4/vnnsWDBAnz44Ydwu90YMmQIzp07Z2HLiYiMo+fGjTKwqlaJ1n40ahmyXZY3hyLzeWlpzkx+fr7fv5ctW4a2bdtiz549uOWWWyCEwPz58/H0009jzJgxAIAVK1agXbt2WLVqFR588EErmk1ERBpouZj369zavIY1Eu4y5FAjFnZZ3mxnUiUAl5eXAwDS0+uzoouLi1FaWoqhQ4f6HuN0OjFgwAC8//77DGaIiGwg0ou5WdMb4SxDVpNLYpflzXYmTTAjhMBjjz2G/v37IycnBwBQWloKAGjXrp3fY9u1a4evv/464HFqampQU/ND8amKigqDWkxERGpEcjE3M/HUuwxZaeNPb26LdxmyUh6Qd88ibx6Q1uOSdtLUmZk6dSr27duH1atXN7nP4fCPwIUQTW7zmjNnDlwul++vQ4cOhrSXiGKLUXVHYkG4tUrM3jBSSy0XLXlAVtWIiSVSBDOPPPII1q9fj23btqF9+/a+291uN4AfRmi8Tp482WS0xuvJJ59EeXm57+/YsWPGNZyIYkL+gRL0n1eAcUsK8WheEcYtKUT/eQVS7BZsB/FxDtzW0xPwwu/V+GJuVdKwt5aL2+U/SuR2JfmtuNKa1Kv2uBQeS6eZhBB45JFH8Oabb2L79u3Iysryuz8rKwtutxtbtmzBtddeCwC4cOECduzYgXnz5gU8ptPphNOpvPssEZEWaqcSqClvrsuWg6V45b0jio/75S1ZTfrQyqThYTkeDMl2657Uq+a4FB5Lg5kpU6Zg1apVWLduHVJTU30jMC6XC8nJyXA4HJg2bRqeffZZdO3aFV27dsWzzz6L5s2b495777Wy6UQUA0KNDjhQPzowJNvNC1IjgXJdlKz/pASPD7tKqhVA3mXISsLNAwp1XAqPpcHMSy+9BAAYOHCg3+3Lli3DxIkTAQCPP/44qqqq8Ktf/cpXNO/tt99Gamqqya0lolhjlyXFslEazVISqA9lXwHEpF65WD7NFIrD4UBubi5yc3ONbxARmcYOVW6tHh3QSoY+DTaaFUzjPpQ9WLDLnkWxQpql2UQUO+yy/5DsowMNydKnoUazlASajpE9WLBi40cKjBtNEpGprNijJ1zePXVCjQ5YvaeOTH26rug4Hs0rUv34UH0oS5AWjAwjYtFIy/WbIzNEZBq7JdSqHR0AgF2Hyyy5mOnZp3pclLWMUqkZYbHDCiAm9VqPwQwRmcaOCbWhphIANNkR2cyRA736VK8RkFC5Lg2pnY4JJ1jQIzDjiIt9MJghItPYLaHWS2l0YMvBUstr0OjRp3rW0gk2muU1+aZOGJztNiw40CMws8P0Fv1AigrARBQb7JRQ25h3dGB0r8t9owRWVKhtLNI+NaLSrlK1W48rCYvH98aMUT3Qr3NrwwKZSLdAMHsbBYocR2aIyDSyL7fVQpYps0j71Kj3YUWuix75Q3bL66J6HJkhItNE04Z7skyZRdqnRr6PxqNZRn+uWvdLMuoYZD4GM0RkKiM33DNzZ2uZpswi6VOZ3kek9AjMZAlSSRtOMxGR6YyYgjA7YVO2KbNw+1S29xEJPQKzaAruYglHZojIEnpOQViRsCnjlFk4fRrO+zBzBEwLb2Cm9K4dqA9wgwVmehyDzMdghohszYjVOGoZOWVmBKUgRMv7yD9Qgv7zCjBuSSEezSvCuCWF6D+vQIoVPnoEmDIGqRQatzMgIlvbdbgM45YUhnzc6gf6GraqyA7F1dRMw4V6HzJtmxAM68xEBy3XbwYzRGRravcCenFsL4zudbnxDZKQHkGId58qpZU+suxT5cUKwPbHvZmIKGYwYTM4veqmyFJXRy099kvinkv2wWCGiHRjxS9ZI1bjRNMvcr2CkEiWLEdTf5KcGMwQkS6syjFQu7O12otntOVK6FU3JdwRsGjrT5ITVzMRUcSs3stGr1VFVr8PI+g1DRfOkuVo7E+SE0dmiCgisuxlE2khPlneh970mobTOgIWrf1JcuLIDBFFRKa9bCIpxCfT+9CTnnVTtIyARWt/kpw4MkNEEYmWvWyi5X0E4g1CGueuuMPIXVE7AhbN/enFxGZ5MJghoohEy9LoaHkfSvTcD0vNkuVo708mNsuF00xEFJFo2csmWt5HMHruhxVKNPcnE5vlw2CGiCISLXvZRMv7sFLDvZ92F5/GjBHR159G7AUm68addsJpJiKKmJ45GVrpmbdg5fsIh0w5G0rTLr+8JQvrPymxRX+qoXclZE5X6YN7MxGRbsy+uBp1IZApSFAi00Uw1N5PC++9Fq1SnFL3p1p67gVml407rcKNJhtgMEMkB70DhFi+EMj03u22AWWk9NqlPdb6LRzcaJKIpKL3KILdCrLpGcjJ9t7ttgFlpPQqQhhr/WY0JgATkaGMWPlhp4Js+QdK0H9eAcYtKcSjeUUYt6QQ/ecVhL3iRbb3Hgv1ZBrSK1E81vrNaAxmiMgwRqz8AOxzITAikJPtvR85dV7Xx9mBHnuBRXsdHrNxmomIDGPUULrRFwI9poWMmg6S6SKYf6AE87f+R9Vj8z48iqmDukgx7aeHSIsQ6jVdRfUYzBCRYYwaRTDyQqBXfo9RgZwsF8FgwVog0Zj/oaYScrDnatm4k4LjNBNRFJGt+JZRowhGFbjTc1rIqEBOluJ+oYK1QKye9pONHtNVVI8jM0RRQqa6I15GjiLoXeBO72khI6eDtL73YNNm4U6phROYMP+jKT33zIplDGaIooBS3RHviIJVv/KMHkrX80Kg97SQ0dNBat97sCAXQNgBsJbAhPkfwUUyXUX1OM1EZHNGrRjSi9FD6Xptnqj3tJAZ00Gh3nuwabOHVu7FQxFMqYXaSNKL+R9kBo7MENmcHYpv2WEo3YhpIav3rAoV5Aaidkot2KhbQ3beh4nsg8EMkc3JVndEiexD6UZNC1kVyIWToOulNgBWCtbSUxJwR6/LMTjbLV3QStGJwQyRzclUd8TOjMzvsSKQ0yN4VXMMO4y6UfRjzgyRzYXKXXCgPqmTyZehRdNSWT2CV7XH0CtviShcHJkhsjkW39JXtIw0hJo2C4arj6KH3rvVy4rBDFEUUM5dSMTs0Tm2GlGQgez5PWqECnJFgP/2/htgABwNZKw9ZRROMxFFiWE5HswYcRXSUxJ8t5VVXsDsTQfD3qGZ7C3YtNni8b2xOEqm1KgpIzY5lZlDCGFtvXODVVRUwOVyoby8HGlpaVY3h8gwSoXzvL+t9bhAxcqQdbTRqwKwnT9/O7ddq9o6gf7zChRXs3mnEXdOHwQA0vaLlus3p5mIooBROzQ3FEtD1tEm2LSZ2ik1O3/+dm57ONTWnlpQ8CXyPjwaFf3CaSaiKKClcF44Ym3ImvzZ+fPfvO9ERJWO7UjtsvwXtv4navqFwQxRFDCycJ7s2yWQsez8+W/eV4Kpqz8OeJ/sbY9EJMvy7dovDGaIooCRhfOMHvUhdWrrBHYdLsO6ouPYdbjMtAuNXT///AMl+NWqvQjWTbK2PVJq981SYsd+Yc4MURQwcodmM7dLiKUkzWAa98OZ71elWZHbYPV2GeGcE97RJLWs3upDb2qX5Ydip35hMEMUBYwsnGfWdgmxlqSpJFA/BOLNbTB6GbWV22WEe05o3ZcqGrf6CLbJ6djrO+CFrYdCHsNO/cJghihKGLVDs5GjPl5Ky8rNumDLQqkfAtFrlVooZnz+gURyTmgZUYjmrT6UqlkDQN6Hx0z/TI3EYIbIREZPoxhRit/o7RLMWFZuB8H6QYna3a0jYcV2GZGeE1pGFKK90rHS0vto2wKFwQyRScyaRtGzFL83+Kq5VIdpg7ti9e6jKK2o8d0f6agPoC3B1O5bDASjdWqkoZPnqg0NlI0a9VMS6TmhZl+qOAewYNy1MTHiF4jZn6nRdAlmamtrsX//fmRmZqJVq1Z6HJIoqthxGiVQ8OVOS8JvBndDpzbNdbtgWp1gKotI3t+RU5VNKr7qHSibuQFnpOdEsNEkrwXjeuPWa+T6f85s0bKpKhDm0uxp06Zh6dKlAOoDmQEDBqB3797o0KEDtm/frmf7iGzPjnU6lIqkfVtRjflb/wNnszj069xaly89KxNMZRLO+3MAaNU8AS9sPWRK8TPvqN/oXpfr9vkHosc5obQvlef7faliPZDxMuszNVpYwcy//vUv9OzZEwCwYcMGFBcX4/PPP8e0adPw9NNPqz7OO++8g1GjRiEjIwMOhwNr1671u3/ixIlwOBx+f3379g2nyUSWsVudDrODLzU1MaI5SdNLa20Q7+OUPgVZA2U1QvWFA+rOiWE5HuycPgirH+iLF8f2wuoH+mLn9EHSjYKazaqaRUYKK5g5deoU3G43AGDz5s24++670a1bN0yePBn79+9XfZzKykr07NkTCxYsUHzMsGHDUFJS4vvbvHlzOE0msozdplHMDr68UwIAFC9eVRdrseVgqS6vZyYtFw01/dBQq5QE/PonXXH2/EXFx8gWKKsVrC+0JqhGy8iDXvIPlKD/vAKMW1KIR/OKMG5JIfrPK7Dd9gWNhZUz065dOxw8eBAejwf5+flYtGgRAOD8+fOIj49XfZzhw4dj+PDhQR/jdDp9gRORHdltGsWK4Ms7JfDEmv0BL87l5y9Km1ukJJyEb6WkTI8rCSOv8eCNvcdxuvICAOB05UWseP+IqrbIEihrMSTbjWmDu2LZe0dwtuqHc8KuCapWCFR8ccoqe+XuqRVWMDNp0iT87Gc/g8fjgcPhwJAhQwAAH3zwAbp3765rA7dv3462bduiZcuWGDBgAJ555hm0bdtW19cgMpJVdTrCZVXwNSTbjdz1nwa8z25LtCNJ+A6UlKl0EWp4kQ9GlkBZrUCBYMvkBEy6KQtTB3WR/vOXQaA+jHMEnpa02/9fgYQVzOTm5iInJwfHjh3D3XffDafTCQCIj4/HE088oVvjhg8fjrvvvhuZmZkoLi7GjBkzMGjQIOzZs8f3mo3V1NSgpuaHpaMVFRW6tYeih5ll862o0xEJq4Kv3cWn/ZZ9N2aXJdp61M1puLy+tk6g/7wCTfVnvGQLlNVQCgTLqy5i/tb/4Ep3C9uOHphFqQ/V7lMl8/9fSsJemn3XXXcBAKqrf4j6JkyYEHmLGrjnnnt8/52Tk4PrrrsOmZmZ2LRpE8aMGRPwOXPmzMGsWbN0bQdFl2DD/0YtU7RTTQergi+1UyGlFdXYdbhM2qWketfNCbf+jIyBcigsoBi5cIovNmTHKUkgzGCmtrYWzz77LBYvXoxvv/0W//nPf3DFFVdgxowZ6NSpEyZPnqx3OwEAHo8HmZmZOHRIeU+JJ598Eo899pjv3xUVFejQoYMh7SH7CTb8/9DKvWjZPMEvZ0PPWh12qulgRfCldipk9sZPcbrSmM+ooXBH7/TOOdqqMvG5ZXKC7XNLWEAxcpEUXwTsNyXpFVYw88wzz2DFihV47rnn8MADD/huv/rqq/HCCy8YFsyUlZXh2LFj8HiU/+d0Op2KU1AU29QsOW6cfKp3Ypye1XmNZnbwpaZqKwC/QAYwJnkxkmrNeuYc1dYJvFl0XNXxFt7XG3EOh/SBcjB2W/kno3D7xo5Tkg2FtTT71Vdfxcsvv4z77rvPb/XSNddcg88//1z1cb777jsUFRWhqKgIAFBcXIyioiIcPXoU3333HX73u99h165dOHLkCLZv345Ro0ahTZs2uOOOO8JpNsW4cH6x2LlWhx7MXNaqZjluIHp/RkoFA9UUoautE6gTAi2TExQfo7ZGClB/zjYO3gJpnZKIvle0tv0SZLut/JNRuMUXAXtNSTYWVjBz/PhxdOnSpcntdXV1uHhRXXY9AHz00Ue49tprce211wIAHnvsMVx77bX4/e9/j/j4eOzfvx+jR49Gt27dMGHCBHTr1g27du1CampqOM2mGBfuLxa71uqwI6WqrekpiUGfp9dnFEnBQG/9jvv+9oHiKiOtFw215+zoXhm2vQg1pFexvFimpvhi41PF7Uqy9bJsIMxpph49euDdd99FZmam3+3//Oc/fYGJGgMHDoQQyr+k3nrrrXCaRxRQpL/mYmFo28xVXkoCTW+VllfhN69/EvK5kX5G4eZsKOViNaY1j0XtOTskOzpqcdlt5Z+M1PThgnHXolWK09ZTko2FFczMnDkTP//5z3H8+HHU1dVhzZo1+OKLL/Dqq69i48aNereRSBdqczKURPvQtlm7eqvROLdo1+EyVc8zK2Bt+Dg1q0daNk/AwnG90Vfj9I+aczbaRirstPJPVrHYh2EFM6NGjcJrr72GZ599Fg6HA7///e/Ru3dvbNiwwVdAj0g2anbSDcTuiXFqyL6rt1m1b8LJ2VCTi3X2/EV8XlqBvhqTv2N1pMJOK/9kFWt96BDB5nmiQEVFBVwuF8rLy5GWlmZ1c0gCAauLfr8kW+mCYeXF3OipH29RNqULsjdQ2Dl9kKVfhN6ACzDuM/L2RaigqWFfrCs6jkfzilQdP9yRLplGzYjMouX6zWCGYlKgAGHLwVLpLhhmXMR2HS7DuCWFIR+3+oG+li8rN6M/tAZNavsv2DHUkCGfichMhgQzrVq1gsOh7n+c06flWfXBYIa0kOmCoTT1o/dokdqRhRfH9sLoXpdH/HqRMuMz0hI0hRrNaUyWkS4i2Wm5fqvOmZk/f36k7SKSnixF7cws62632h5mfEZa8g205mKxii2R/lQHM3rvu0REysws6263Xb3NoiVoUlo9EkwsLPUnMktYRfMaqqqqQkVFhd8fkZVq6wR2HS7DuqLj2HW4zJaVe80s666m8m40rpjR27AcD3ZOH4QZI65S9XhZRrqIokFYS7MrKysxffp0vP766ygra1r/oba2NuKGEYUjWlZ9mD31E4t1KYwQH+fAxJuy8LedxRzpIjJRWMHM448/jm3btmHRokW4//77sXDhQhw/fhz/8z//g7lz5+rdRiJVZK+VooUVUz+xVpfCKLFaG4bISmEtze7YsSNeffVVDBw4EGlpadi7dy+6dOmCv//971i9ejU2b95sRFvDwtVMscEutVK0MKOuigxkWkGmp2gZJTSbmvMhWs8Z8mfIaqaGTp8+jaysLABAWlqabyl2//798fDDD4dzSKKImJkw62X0F2osTP1E8wWfI13aqTkfovmcofCFFcxcccUVOHLkCDIzM5GdnY3XX38dffr0wYYNG9CyZUudm0gUmpkJs4B5X6hmXxDNqDbsPf6RU+cxf+t/omJaUIksS/3tQM00MYCwp5I5mhPdwgpmJk2ahE8++QQDBgzAk08+iREjRuCvf/0rLl26hOeff17vNhKFZGbCrNm5OWZdEI0O0AIdPxC96+iQ/NTUVcpd/ykAR1i1lziaE/102c7g6NGj+Oijj9C5c2f07NlTj3bphjkzsSGcPXUieZ1oys0BjK82rHT8UGTYQoGMp2VLiFAanzNmVdIm/Wm5fmuqM/PBBx/g3//+t99tr776KgYMGICHHnoICxcuRE1NjfYWE0XIrFopWnJz7CLUr2Kg/hdvuPV6gh0/FBaWiw16fs4Nj2X0uU3y0BTM5ObmYt++fb5/79+/H5MnT8bgwYPx5JNPYsOGDZgzZ47ujSRSw5sw63b5TyW5XUm6/fpS+6X73penbPMFqXeA1rhoYeHhMtVVcRuL9sJyshd4NKt9en7ODY8VjT8+KDBNOTNFRUWYPXu27995eXm44YYbsGTJEgBA+/btMXPmTOTm5uraSCK1jE6YVfulu2Dbl3hj7ze2mJPXM3k6UG5Cy+QEzW2KhcJysudxmNk+NXWV2qU5ATjwbYX62ktmLwwg62gamTlz5gzatWvn+/eOHTswbNgw37+vv/56HDt2TL/WEYXBmzA7utfl6Ne5ta65K94vXTVH9CYE5x8o0e31jaBX8rQ3N6HxL+GzVRc1tScaC8s1HuHYvO9EwL6S5ZxR+iyNap+aaeLc23og9zZtU8l220RVNrKPHDakaWSmXbt2KC4uRocOHXDhwgXs3bsXs2bN8t1/7tw5JCRo/xVGZBdadki2y6ocPaoNR5IX01g01dEBAo9wxDkCnzsynDNm7tjekNq6SlpqL9lhE1VZl4zLPnLYmKZgZtiwYXjiiScwb948rF27Fs2bN8fNN9/su3/fvn3o3Lmz7o0kMkK4XyJadkg2olif3vQovx8qN0GJ9/V+M7grOrVJkerL3CuSi43SSppgP3CtPmesKEDppWaaWMtUsuxbS8gaMNhxaxhNwcwf//hHjBkzBgMGDECLFi2wYsUKJCYm+u5/5ZVXMHToUN0bSaS3SL9EvF+oL2z5Agu2HQ75eNnn5COtNqz2/bVMTvCbdpJ9FCaS8yTS0Sqrzhmr80zU1FXSUntJ1krasgYMVo3MRUpTMHPZZZfh3XffRXl5OVq0aIH4+Hi/+//5z3+iRYsWujaQSAs1v6L1+hKJj3Pgpi6XqQpm7DAnH0nytNr3t/C+3ohzOKQbUg8k0vMk3NEqL6vOmWjJM2n8XbDj//0Ye74+I8W5J3PAYOXIXCTCqgDscrkC3p6eHr0rD0h+an5F6/0lItucfKTz7+FWG1bbD32v0Dch2yh6nCfhjlxYncch2zkdjmDfBaN7XW5hy+rJHDBYPTIXLk2rmYhkpXb1hd51J8wq1qdG/oES9J9XgHFLCvFoXhHGLSlE/3kFpqyMkakf9KDHeRLOyIUMfWX3z1Lpu6CkvBoPrdyLF7f+x/JVOTIHDHYdmWMwQ7anpcqnEV8iZhTrC8XspbSByNAPetHjPFGzjL9xPCBLX9n1s1STp/TC1kO4aa45Qb4SmQOGUOetA/WjXLKNzIU1zUQkEy2/oo36EjF7d+uGZJp/D6cfZFyaqsd5omYlzYJxvdEqJVGq9+41LMeDQd3b4e+7juDr0+eRmd4cP+/XCYnNtP8GNuszVpunVFphbZKtzFN5sq8AU8JghmxPy6/okddkGPYlYtbu1o3JNv+upR9kXZqq18VG1pU0agT6bP62s1hzu838jLVOy1iVZCt7wGDH85bBDNmell/RoYreCQAzRsj3qyMYmeffg5F1aSqg78XGylG7cOn12Zj9GWsZUbUqydY7SlVzqQ7TBnfD6t1HUVohX8Bgt/OWwQzZntZf0aGK3s3edBBxcbD8y0Qtmefflcg0NaZEz1+nVo3ahUOvz8aKzzjUd0EgZgb5gUap3GlOaYtG2um8ZQIw2V44qy+G5XgwY8RVAY8ny/44aqlJ2GudkojS8iq//VWs3HfFLrsZD8vxYOf0QVj9QF+8OLYXVj/QFzunD7JNoBsOvT4bMz9j77m8cd8JjL2+g6ZChWYF+UpJ+t9W1GD+1kNwNovTfS+5WMKRGZKK3lsMKP2Krq0TmL3ps4DHkmVkQC01U2dllRfwm9c/AVCfr3BbTw/Wf1JiWa6KnabG7PTrVA96fTZmfcYBd2pvngAIgbNVlxSfZ2aSrdGjVDIm0ZuNwQxJQ68tBtT8Ty1b0myktOwXVVJejf95p7jJ7Wbmqthxasyr4YWjTYoTcACnvquR+iKi5WKn12ej9jinztVgXdHxsPpPKSen/Hz9lhkjr/Fg476mI6xmJ9ka+X0jaxK92RjMkBT03GJAzZeBnUYG1GoYzJVWVGP2xk9xuvJi6Cd+z8wRKZmXpgYT6MLRkIwXEa0XO70+GzX5K3EO+I2Qauk/NaMde74+g0X3XovZmz6zdFWOUd83MifRm405M2QILfkYWore6aVNC6euj5OFN5hzpyVpCmS8vL8Ql79XbGgujR2rzCrlPDQkW75VOMUU9fpsgh3Hq/Gp5a3Su3nfiaDHBtSPdrRKcVqe92TESKQV35sy48gM6U7rL0FLpnzU/v8t+feA0vRBpCNK4f5a1sJOtSzU7oAtU75VJHkaen02SseJczQNZBqauvpjLIADt16j/DpaRjusznsyYiQy2qbKI8VghnQVzrCnFVM+pyprdH1cOCJN2gsWNOqZa2LkkLVdallo2QFblouI2otd4VdluKlLmyb36/XZND7OqXM1isn3XnUC+NWqvVgcp3zO2SnvyogiedE4VR4JBjOkm3B/CVrxpWT1F2GkSXuhgsaF9/bWXG9DidGjDVb/alYjnAuC1RcRta8/5R97MffOqwOed3p9Ng2Ps67ouOrnBTvn7JZ3pfdIpNXfYbJhzgzpJty6EkZsbBYqZ6dPVjrcacr5MEZuphbpppBq5spnbzroq6OjR+ghS90Xq4RzQbD6IqL29c9WXTQ1z6dNivo8tGDnnB3zrvSsW2TXDSGNwmCGdBPusKfeX0r5B0rQf14Bxi0pxKN5RRi3pBD95/nvkrvlYCmqL9UFfL6RX4R6JO1pSXwMtPOxx5WEB2/Jgsel/WIbzmiDlcX59KJmB2wvWS4iWtoMmJgsqvF/qWDnnB139/aOUo3udXlERfLsGMwZidNMpJtIhj31GoJVk7MDIOBjvFzNEzB3TOBh90jpkbSnJWgc3etyxbyHx4ddpSmPAdA+2hAtNTBCFSb0kuki0rDNoZiZ53PqO215aKHOObvkXRnBTkn0RmMwQ7qJdA470i8lNTk7ues/BeAImkeSnBCPIdluVa+plR5Je1qDRqW8h4a319YJ/G1nsa75B9FWA0NNYULZLiLeNj/xxn6crQq9VN+MPB8tAbHaES475F0ZJZaDuYYYzJBu9MjYj+RLSc2oR2lF6F+FRv5C1SNpL9KgUWkVVSSfXeNj/iizlfQbSYaj8YXDDhWAh+V4kOpMwH1LPwj5WDPyfLRsBinDCJcdxHIw58VghgIya48kPen5q9KoX6h6rMCIJPAINe0TzmcX6JjpKQlBi/bJsnw5HHa8cPTt3FqalT9qpuxaGjjVS9GJwQw1sXlfCf573QGcrrzguy09JQF39Locg7PdIQMbq4Y9rVi6rZVe9SbCCTzUTvto+eyUjqm2+rDVy5djhRF1TiKhdP62bJ6ASTdmYeqgLhyRIU0cQgj7LS3QoKKiAi6XC+Xl5UhLS7O6OdKbs/lgwE0IG5I1gbO2TqD/vIKIaqt4f6HunD7I0C9TvRJj1Y6geftGaRounPcd6phqrH6gr+1GOexMtoRs7vZMwWi5fnNkhnw27zsRMpAB5E3gVLviJBQzfqGGGgFR+yWvdsrDiNLnWqriNiZbQbNYIVuyqB2n7EhODGYIQP3F87/XHVD1WJkTONWsOFGSnpKAZ+/QPk8fKPl1z9dnwg5EjPj1bETp83CniGRavkxE0YHBDAGo/5WtZZdlmRM4G/76LC2vwjv/+T+8WRR6F94ZI3toDhYCBR6NN9HTc5uCcEfDjCh9rvax6SmJfvlXVi1f5pSGfNNMRHphMEMAwv+VLWsCZ3ycA+VVF/DcW1+oHqFxp2kvCBco8GhcRFVtIBLJLsehGLGPjdpj7vh/P1Y1UmUkXsSjr+4PUUPczoAAhL96p00Lp5Sl6pX2Pwok3L2flAKPxvTepmD5e8Wa+9uI0udqj5nYLE6X8u3hinQvrGigxzYaRDLjyAwB+OFXttpRDAfql1H+9vUiv0J0Mvza1RJohHsh15r8quc2BQ23HdDS30bUANLjmLV1AoVflWHX4TIAAv2uaIO+OgU9Ro522YkRCeBEMmEwQwD8VwKFCgK8K4XOnG+aYyPDkLWWQCPcC7kR03LhjI5p7W8jVrNEcsz8AyV4Ys1+nG1wLi3Ydli3omm8iNczIgGcSCacZiIf76/sxrspOxpdk9yuJLRMDhwHi+//rByyVvuFPPXHnbFz+iBDE2q1PE/rLsdAeFMEeu3aG+kx8w+U4KGVe/0CGa+z5y/iIZVTQMF25eZFvJ4RCeBEMuHIDPkJ9Cu78VLjwq/K8OL/Hgp6HCt/7ar9Qr6py2VhX8i17C8DRL5NQTB2HF2orRPIXX8w5ONy138adAooVGIvL+L1jEgAJ5IJR2aoica/shsmcJZXXQgZyHhtOVhqcEsDCzXCEU7Cb2PBkl8DvR6gbZsCt0v7xdVOowu7i0+jtCJ0e0srarC7+HTA+9Qk9ppxLtiBEQngRDKxNJh55513MGrUKGRkZMDhcGDt2rV+9wshkJubi4yMDCQnJ2PgwIH49NNPrWks+ZIp1VpXdMKSqSYtX9zBpihCUQo8Gl8P3K4kTTlEw3I82Dl9EFY/0Bcvju2FGSOuUvU8O40uRFqcT+3qHAC8iH9P6XzVen4SycjSaabKykr07NkTkyZNwp133tnk/ueeew7PP/88li9fjm7duuGPf/wjhgwZgi+++AKpqakWtDi2aV3BU1Z5wbKpDzWrbPSoPaJmWi6cBNuG1YFr6wT+trM4qqYIIi3OpyWx18qd3GUj23YGRHqxNJgZPnw4hg8fHvA+IQTmz5+Pp59+GmPGjAEArFixAu3atcOqVavw4IMPmtlUQnjTGFZOfQT74tazgFigbQn0DOBk2/FYD32y0uFOSwo51eROcwYM0rQm9vIi/gPuh0TRSNoE4OLiYpSWlmLo0KG+25xOJwYMGID3339fMZipqalBTc0PdU8qKioMb2usCGcaI5Kpj0Dl5wFo3pyx8Re3lbVHtL4nr2gbXYiPcyD3tmw8tHJv0Mfl3tYj4GcQTmIvL+JE0UvaYKa0tD55tF27dn63t2vXDl9//bXi8+bMmYNZs2YZ2rZYpWUFT6RTH4GmgFo2TwAAv6W83mkhAKqnjKyqPaL4noTA2apLvtvcaU7k3tZ0n6hoG10YluPB4vG9m9SZARCyzgxX5xBRQ9IGM16ORkVOhBBNbmvoySefxGOPPeb7d0VFBTp06GBY+2SjZjO9cDfc8053hPo1HenUh9IUUKB6JKXl1YrtUZoysqL2iKb3VFGDh1buxeIAU13RNrrgDdC0VgCOxqk3IgqftMGM2+0GUD9C4/E0uBCdPNlktKYhp9MJp9NpePtkpCah1YwN9yKZ+tCyFQEQvBaL0pSR2bVHtL4nryfW7I/6MvtAfWByU5c2uKlLG03Pi7apNyIKn7TBTFZWFtxuN7Zs2YJrr70WAHDhwgXs2LED8+bNs7h18lGT0AogoqRXNUuz01MSsOP//RiJzcJb9a91xVQogaaMzJ6iCPc9nT1/EYWHy3BTV20X+VgSbVNvRBQeS4OZ7777Dl9++aXv38XFxSgqKkJ6ejo6duyIadOm4dlnn0XXrl3RtWtXPPvss2jevDnuvfdeC1ttHrXTQWoTWoUQESW9qrkon668iD1fnwl7KsSo1U+l5VW+/244RRGIAHBbT49uF8RI3tOur04xmAkh2qbeiEg7S4OZjz76CD/+8Y99//bmukyYMAHLly/H448/jqqqKvzqV7/CmTNncMMNN+Dtt9+OiRozWqaDCr8qU5XQGoyeuzpHcvE2qvDb7E2fITkx3td3w3I8+OUtWfifd4oDPv7ld4pxbcdWukxVRPaeOMJARBSKpRWABw4cWD9a0Ohv+fLlAOqTf3Nzc1FSUoLq6mrs2LEDOTk5VjbZFGrKtDd87JR/BE/I1UKPXZ0juXiHs9miGmcqL/j1XW2dwPpPgm9iqNdmmd73FA6OOBARhca9mSSjtkx7bZ3wBT1nq5quiAlXJLs6m73nkdrHAE37Tsvy7Eg1fE9atGqegL5XMJghIgqFwYxk1F5kCw+XqV4h4w0y3GnOiAIRszarU9pDplXzBF+tGS+3KwmLx/fG4vG9kZ7if19jDQMUs5dnD8vxYNG9vZvs2xTMnDFXM5GViEgFaVczxSq1F89dX53StELGG4REWpfDrOWwSqtUAOVquVUX6/Cb14pCHtv7XDX0zOG59RoPFuBa/GrVx0Efp/dSeSKiaMdgRjLqL57qfrE3rqSqRyBi1nJYpVUqSnkk7jT1AYpVFWRvvSYDi+McTT6D1imJGN0rA0Oy3VxaTESkEYMZyai9yPbr3BoLtn0Z4BH+pgzsjCHZbt+/9QpEZFwOqyVAUVNBdsaIqwwJ2FgbhYhIXw4hROTLNSRWUVEBl8uF8vJypKWlWd0cVfIPlAQs0e+91L00vjeGZLvRf16Bqn2S7DBtEe4WC415k6KBwAFK48KASkvgb+vpwfpPSsKulKzX+yEiilVart8MZiSUf6BE1eZ7ShfuxpQu5LKIdIuFxoHDmcoLmL1J/fECPX/KqqaVktX2oxlbRhARRTsGMw3YLZhR2pYAqL+YqhlZCMQ7xbJz+iCpRgiU3m+kgcOMEVehVYpT88hIbZ1A/3kFiv0Zqh8jfT9ERFRPy/WbS7MlomZDwsaF3IbleLBz+iDMGHFV0GPrWTdFL1pq6gQSrLjglFUfo7zqAkb3uhz9QuzA3FAk9WcifT9ERBQeBjMSCfdCGh/nwImzVYGf1IhRex8FU1snsOtwGdYVHceuw2W+i7mMgUMk9WfMLMRHREQ/4GomiYR7Ic0/UIKl7x1R9Vyj9j5SEix/pOZSnapjRBo4aFl1FUn9GbML8RERUT2OzEgknAupd4QiFD22GtAq1B5TR05VqjqOmYFDJFs2WFGIj4iIGMxIJZwLaagRCi8BfbYaUEvNNNDq3UfhTpMrcIhkywYz9q4iIqKmGMxIJJwLqdqRh1/c1MnUVTRqpoFKK2pwbUcXBOQKHJT2hnK7koKuRjJr7yoiIvLHnBnJKO195EpOwKSbOvlV8wXUjzw0fp7R1AZZ/z7wLQDA4QAaFgkItcWCmgq+kQQO4VbpNWvvKiIi+gHrzEiqtk5gQcGXWPZeMc5W/VA8r3HxNW9dlFAl/M2uL7PrcBnGLSnU/LzJN3XCYA37E8laoI4VgImIIsOieQ3YNZjRUnxNawl/M4QKsgIJN/Bi4EBEFH1YNM/mtNZQCTfHw0jB8keUhFuHxbvppdYCeUREFB2YMyOhcGqoyLgTs1L+SCisw0JERFowmJFQuDVUvCMUMmkYZL335Sks2PZlyOewDgsREWnBYEZCshRf0ysXxRtk9clKxxt7vwmZrMw6LEREpAWDGQl5a6gES56NcwBnKi8Y1gYjVgkZvZyaiIhiExOAJdQweVZJnQCmrNqL/AMlur9+qG0IInlNGZOViYjI3rg0W2Kb953A1NUfQ2njZyNqyHiXVCsl7Or1mlxOTUREwWi5fnOaySJqLuatUpyKgQygbmdorUGDUbtRNyZjsjIREdkTgxmTNAwqjpw6j9W7j6K0Ing+itZVTY0DlzOVNZi96TNNeS9G7UZNRERkFAYzJgiUTNuYNx+lYd6IllVNal5D6XUaH0vtaxIREcmACcAGU0qmbSxQZV+1O0OfqaxR9RpKr9OQkbtRExERGYHBjIGCbUsQSONy/vFxDtzW0xP0+TNGZGP2ps9Uv0ag12ko2DYEXD5NREQyYjBjoFDJtEq8+Sj5B0rw8jvFio/75S1ZaJWSGNZrNHydxrh8moiI7IQ5MwYKN0m2bWqSqlGd9Z+UoLs7/OXmwfJeZNzriYiIKBAGMwbSmiTbsJy/mlGdkvJqnA6jCrDabQO4fJqIiOyA00wGCpVM21DjfBS1ozrpLZyqX6Mh5r0QEVG0YDBjoPg4B2aMuEpVcm7jfBS1ozrutKSQWx80Nm1wN+a9EBFR1OA0k4HyD5Rg9qbPAt7nTnNiXJ+O6NQmJWA+yo8yWyHOgaAVgB2O+sclNovDS+N744k39uNs1cWQ7erUprnm90JERCQrBjMG8daXUYpFfj+yB269Rnl0ZM/XZ4IGMgAgBPDS9i/x6PcjLanOBNy39IOQbWPBOyIiiiacZjJAqJVIDgCzNwUuWuelNmdm2XtHfMfp27k1C94REVHMYTBjAC2bNSpRO3pytuqiX5E9FrwjIqJYw2DGAHps1tgnKx0tkxM0H4cF74iIKNYwZ8YAemzWGB/nwKSbsvDC1v9oPg4L3hERUSxhMGMAb32Z0vLqgHkzaovWTR3UBcveL8bZ84FXKAU7DgveERFRrOA0kwH0yl2Jj3Ng7pirA97HHBgiIqJ6DGYMokfuSm2dgCs5EZNv6oT0FP/8GebAEBER1eM0k4EiyV3JP1CCWRsO+q2KSk9JxO29MjAk280cGCIiou8xmDFYOLkrSgX3zlRewLL3jjCQISIiaoDTTCaorRPYdbgM64qOY9fhsqDF8oIV3PPeNmtD8IJ7REREsYQjMwYLNF3kcdVvDunNd6mtE76pqFPnalQX3ONqJSIiIgYzhlKaLiotr8bDK/fipfG9AaBJsKOG2sJ8RERE0Y7BjEFq6wSeWLNfcbrIAeDJNftxRqGGTCjcLJKIiKgegxmDLCg4pFjsDqgPaMIJZNQW3CMiIooVTAA2wIVLdXj53a90Py4L5RERETXFYEZn+QdK0HfO/6Kyplb3Y7NQHhERUVOcZtKRUsJvJGaMuAptUp3cLJKIiEgBgxmdBKsPEy53mhMTb8piAENERBQEp5l0srv4tObl1aGM69ORgQwREVEIUgczubm5cDgcfn9ut9vqZgVkRN2XTm1SdD8mERFRtJE6mAGAHj16oKSkxPe3f/9+q5sUkNq6L+kpCfjN4K66HpOIiCiWSZ8z06xZM2lHYxrqk5UOjysJpeXVinkzaUnN8PTwq+B2JcOdloRvKwI/lrVkiIiI1JN+ZObQoUPIyMhAVlYWxo4di6++Cl6/paamBhUVFX5/ZoiPc2DmqGwAP9SDaayi+hJ++699uG/pB6i+VOurBNwQa8kQERFpI3Uwc8MNN+DVV1/FW2+9hSVLlqC0tBQ33ngjysrKFJ8zZ84cuFwu31+HDh1Ma++wHA9eGt8bblfo6aHy76v/upon+N3OWjJERETaOIQQeq4mNlRlZSU6d+6Mxx9/HI899ljAx9TU1KCmpsb374qKCnTo0AHl5eVIS0szpZ3eXbBLK6oxe+OnOF0ZeNsCB4B2aU78+We9cOq7GtaSISIi+l5FRQVcLpeq67f0OTMNpaSk4Oqrr8ahQ4cUH+N0OuF0Ok1sVVPxcQ7069wauw6XKQYyQP3+TKUVNYhzODC61+XmNZCIiCiKSD3N1FhNTQ0+++wzeDz2mIJRu1zbiGXdREREsULqYOZ3v/sdduzYgeLiYnzwwQe46667UFFRgQkTJljdNFXULq3mEmwiIqLwST3N9M0332DcuHE4deoULrvsMvTt2xeFhYXIzMy0ummqhFquzSXYREREkZM6mMnLy7O6CRHxLtd+eOVeOAC/gIZLsImIiPQh9TRTNFBars0l2ERERPqQemQmWgzL8WBIthu7i0/j5LlqLsEmIiLSEYMZk3iXaxMREZG+OM1EREREtsZghoiIiGyNwQwRERHZGoMZIiIisjUGM0RERGRrDGaIiIjI1hjMEBERka0xmCEiIiJbYzBDREREtsYKwDqqrRPcsoCIiMhkDGZ0kn+gBLM2HERJebXvNo8rCTNHZXMzSSIiIgNxmkkH+QdK8PDKvX6BDACUllfj4ZV7kX+gxKKWERERRT8GMxGqrROYteEgRID7vLfN2nAQtXWBHkFERESRYjATod3Fp5uMyDQkAJSUV2N38WnzGkVERBRDGMxE6OQ55UAmnMcRERGRNgxmItQ2NUnXxxEREZE2DGYi1CcrHR5XEpQWYDtQv6qpT1a6mc0iIiKKGQxmIhQf58DMUdkA0CSg8f575qhs1pshIiIyCIMZHQzL8eCl8b3hdvlPJbldSXhpfG/WmSEiIjIQi+bpZFiOB0Oy3awATEREZDIGMzqKj3OgX+fWVjeDiIgopnCaiYiIiGyNwQwRERHZGoMZIiIisjUGM0RERGRrDGaIiIjI1hjMEBERka0xmCEiIiJbYzBDREREtsZghoiIiGyNFYDDVFsnuHUBERGRBBjMhCH/QAlmbTiIkvJq320eVxJmjsrmppJEREQm4zSTRvkHSvDwyr1+gQwAlJZX4+GVe5F/oMSilhEREcUmBjMa1NYJzNpwECLAfd7bZm04iNq6QI8gIiIiIzCY0WB38ekmIzINCQAl5dXYXXzavEYRERHFOAYzGpw8pxzIhPM4IiIiihyDGQ3apibp+jgiIiKKHIMZDfpkpcPjSoLSAmwH6lc19clKN7NZREREMY3BjAbxcQ7MHJUNAE0CGu+/Z47KZr0ZIiIiEzGY0WhYjgcvje8Nt8t/KsntSsJL43uzzgwREZHJWDQvDMNyPBiS7WYFYCIiIgkwmAlTfJwD/Tq3troZREREMY/TTERERGRrDGaIiIjI1hjMEBERka0xmCEiIiJbYzBDREREtsZghoiIiGyNwQwRERHZGoMZIiIisjUGM0RERGRrUV8BWAgBAKioqLC4JURERKSW97rtvY4HE/XBzLlz5wAAHTp0sLglREREpNW5c+fgcrmCPsYh1IQ8NlZXV4cTJ04gNTUVDod+G0FWVFSgQ4cOOHbsGNLS0nQ7brRif2nD/tKG/aUN+0s79pk2evSXEALnzp1DRkYG4uKCZ8VE/chMXFwc2rdvb9jx09LSeGJrwP7Shv2lDftLG/aXduwzbSLtr1AjMl5MACYiIiJbYzBDREREtsZgJkxOpxMzZ86E0+m0uim2wP7Shv2lDftLG/aXduwzbczur6hPACYiIqLoxpEZIiIisjUGM0RERGRrDGaIiIjI1hjMEBERka0xmAnDokWLkJWVhaSkJPzoRz/Cu+++a3WTpJCbmwuHw+H353a7ffcLIZCbm4uMjAwkJydj4MCB+PTTTy1ssbneeecdjBo1ChkZGXA4HFi7dq3f/Wr6p6amBo888gjatGmDlJQU3Hbbbfjmm29MfBfmCdVfEydObHK+9e3b1+8xsdRfc+bMwfXXX4/U1FS0bdsWt99+O7744gu/x/Ac+4Ga/uI55u+ll17CNddc4yuE169fP/z73//23W/l+cVgRqPXXnsN06ZNw9NPP42PP/4YN998M4YPH46jR49a3TQp9OjRAyUlJb6//fv3++577rnn8Pzzz2PBggX48MMP4Xa7MWTIEN/+WdGusrISPXv2xIIFCwLer6Z/pk2bhjfffBN5eXnYuXMnvvvuO4wcORK1tbVmvQ3ThOovABg2bJjf+bZ582a/+2Opv3bs2IEpU6agsLAQW7ZswaVLlzB06FBUVlb6HsNz7Adq+gvgOdZQ+/btMXfuXHz00Uf46KOPMGjQIIwePdoXsFh6fgnSpE+fPuKhhx7yu6179+7iiSeesKhF8pg5c6bo2bNnwPvq6uqE2+0Wc+fO9d1WXV0tXC6XWLx4sUktlAcA8eabb/r+raZ/zp49KxISEkReXp7vMcePHxdxcXEiPz/ftLZboXF/CSHEhAkTxOjRoxWfE8v9JYQQJ0+eFADEjh07hBA8x0Jp3F9C8BxTo1WrVuJvf/ub5ecXR2Y0uHDhAvbs2YOhQ4f63T506FC8//77FrVKLocOHUJGRgaysrIwduxYfPXVVwCA4uJilJaW+vWd0+nEgAED2HdQ1z979uzBxYsX/R6TkZGBnJycmO3D7du3o23btujWrRseeOABnDx50ndfrPdXeXk5ACA9PR0Az7FQGveXF8+xwGpra5GXl4fKykr069fP8vOLwYwGp06dQm1tLdq1a+d3e7t27VBaWmpRq+Rxww034NVXX8Vbb72FJUuWoLS0FDfeeCPKysp8/cO+C0xN/5SWliIxMRGtWrVSfEwsGT58OP7xj3+goKAAf/7zn/Hhhx9i0KBBqKmpARDb/SWEwGOPPYb+/fsjJycHAM+xYAL1F8BzLJD9+/ejRYsWcDqdeOihh/Dmm28iOzvb8vMr6nfNNoLD4fD7txCiyW2xaPjw4b7/vvrqq9GvXz907twZK1as8CXNse+CC6d/YrUP77nnHt9/5+Tk4LrrrkNmZiY2bdqEMWPGKD4vFvpr6tSp2LdvH3bu3NnkPp5jTSn1F8+xpq688koUFRXh7NmzeOONNzBhwgTs2LHDd79V5xdHZjRo06YN4uPjm0SQJ0+ebBKNEpCSkoKrr74ahw4d8q1qYt8FpqZ/3G43Lly4gDNnzig+JpZ5PB5kZmbi0KFDAGK3vx555BGsX78e27ZtQ/v27X238xwLTKm/AuE5BiQmJqJLly647rrrMGfOHPTs2RMvvvii5ecXgxkNEhMT8aMf/Qhbtmzxu33Lli248cYbLWqVvGpqavDZZ5/B4/EgKysLbrfbr+8uXLiAHTt2sO8AVf3zox/9CAkJCX6PKSkpwYEDB9iHAMrKynDs2DF4PB4AsddfQghMnToVa9asQUFBAbKysvzu5znmL1R/BRLr51ggQgjU1NRYf35FlD4cg/Ly8kRCQoJYunSpOHjwoJg2bZpISUkRR44csbpplvvtb38rtm/fLr766itRWFgoRo4cKVJTU319M3fuXOFyucSaNWvE/v37xbhx44TH4xEVFRUWt9wc586dEx9//LH4+OOPBQDx/PPPi48//lh8/fXXQgh1/fPQQw+J9u3bi61bt4q9e/eKQYMGiZ49e4pLly5Z9bYME6y/zp07J37729+K999/XxQXF4tt27aJfv36icsvvzxm++vhhx8WLpdLbN++XZSUlPj+zp8/73sMz7EfhOovnmNNPfnkk+Kdd94RxcXFYt++feKpp54ScXFx4u233xZCWHt+MZgJw8KFC0VmZqZITEwUvXv39lvKF8vuuece4fF4REJCgsjIyBBjxowRn376qe/+uro6MXPmTOF2u4XT6RS33HKL2L9/v4UtNte2bdsEgCZ/EyZMEEKo65+qqioxdepUkZ6eLpKTk8XIkSPF0aNHLXg3xgvWX+fPnxdDhw4Vl112mUhISBAdO3YUEyZMaNIXsdRfgfoKgFi2bJnvMTzHfhCqv3iONfWLX/zCd+277LLLxE9+8hNfICOEteeXQwghIhvbISIiIrIOc2aIiIjI1hjMEBERka0xmCEiIiJbYzBDREREtsZghoiIiGyNwQwRERHZGoMZIiIisjUGM0QUkxwOB9auXWt1M4hIBwxmiMhQDocj6N/w4cORkJCAlStXBnz+gw8+iGuuuSbk6wwdOhTx8fEoLCzU+y0QkeQYzBCRoUpKSnx/8+fPR1pamt9teXl5GDFiBJYtW9bkuVVVVcjLy8PkyZODvsbRo0exa9cuTJ06FUuXLjXqrRCRpBjMEJGh3G6378/lcsHhcDS5bfLkydi2bRuOHDni99x//etfqK6uxvjx44O+xrJlyzBy5Eg8/PDDeO2111BZWel3/6FDh3DLLbcgKSkJ2dnZfrv2AvW7+06dOhUejwdJSUno1KkT5syZo8v7JyLjMZghIsvdeuutcLvdWL58ud/tr7zyCm6//Xa0bt1a8blCCCxbtgzjx49H9+7d0a1bN7z++uu+++vq6jBmzBjfFNTixYsxffp0v2P85S9/wfr16/H666/jiy++wMqVK9GpUyc93yIRGaiZ1Q0gIoqPj8f999+P5cuXY+bMmXA4HCguLsaOHTuQn58f9Llbt27F+fPn8dOf/hQAMH78eCxduhSTJk3y3f/ZZ5/hyJEjaN++PQDg2WefxfDhw33HOHr0KLp27Yr+/fvD4XAgMzPToHdKREbgyAwRSWHy5Mn4+uuvUVBQAKB+VKZ9+/YYPHhw0OctXboU99xzD5o1q/9tNm7cOHzwwQf44osvAACfffYZOnbs6AtkAKBfv35+x5g4cSKKiopw5ZVX4te//jXefvttPd8aERmMwQwRSaFr1664+eabsWzZMtTV1WHFihWYNGkS4uKUv6ZOnz6NtWvXYtGiRWjWrBmaNWuGyy+/HJcuXcIrr7wCoH4aqjGHw+H37969e6O4uBizZ89GVVUVfvazn+Guu+7S9w0SkWEYzBCRNCZPnow1a9bgjTfewDfffOObKlLyj3/8A+3bt8cnn3yCoqIi39/8+fOxYsUKXLp0CdnZ2Th69ChOnDjhe96uXbuaHCstLQ333HMPlixZgtdeew1vvPEGTp8+rft7JCL9MWeGiKRx991349e//jUefPBB/OQnPwmZhLt06VLcddddyMnJ8bs9MzMT06dPx6ZNmzBq1ChceeWVuP/++/HnP/8ZFRUVePrpp/0e/8ILL8Dj8aBXr16Ii4vDP//5T7jdbrRs2VLnd0hERuDIDBFJo3nz5hg7dizOnDmDX/ziF0Efu2fPHnzyySe48847m9yXmpqKoUOHYunSpYiLi8Obb76Jmpoa9OnTB//1X/+FZ555xu/xLVq0wLx583Ddddfh+uuvx5EjR7B58+agU1xEJA+HCDShTERERGQT/NlBREREtsZghoiIiGyNwQwRERHZGoMZIiIisjUGM0RERGRrDGaIiIjI1hjMEBERka0xmCEiIiJbYzBDREREtsZghoiIiGyNwQwRERHZGoMZIiIisrX/D5S5Zw19VpbzAAAAAElFTkSuQmCC",
      "text/plain": [
       "<Figure size 640x480 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "\n",
    "plt.scatter(df['TV'], df['Sales'])\n",
    "plt.xlabel(\"TV Ads\")\n",
    "plt.ylabel(\"Sales\")\n",
    "plt.title(\"TV vs Sales\")\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "8a92ecc7-138d-4165-af9a-0be2730232f9",
   "metadata": {},
   "outputs": [],
   "source": [
    "X = df[['TV', 'Radio', 'Newspaper']]\n",
    "y = df['Sales']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "6216e8c0-8a85-4f9b-98d1-4d2d819affaa",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<style>#sk-container-id-1 {\n",
       "  /* Definition of color scheme common for light and dark mode */\n",
       "  --sklearn-color-text: #000;\n",
       "  --sklearn-color-text-muted: #666;\n",
       "  --sklearn-color-line: gray;\n",
       "  /* Definition of color scheme for unfitted estimators */\n",
       "  --sklearn-color-unfitted-level-0: #fff5e6;\n",
       "  --sklearn-color-unfitted-level-1: #f6e4d2;\n",
       "  --sklearn-color-unfitted-level-2: #ffe0b3;\n",
       "  --sklearn-color-unfitted-level-3: chocolate;\n",
       "  /* Definition of color scheme for fitted estimators */\n",
       "  --sklearn-color-fitted-level-0: #f0f8ff;\n",
       "  --sklearn-color-fitted-level-1: #d4ebff;\n",
       "  --sklearn-color-fitted-level-2: #b3dbfd;\n",
       "  --sklearn-color-fitted-level-3: cornflowerblue;\n",
       "\n",
       "  /* Specific color for light theme */\n",
       "  --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n",
       "  --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, white)));\n",
       "  --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n",
       "  --sklearn-color-icon: #696969;\n",
       "\n",
       "  @media (prefers-color-scheme: dark) {\n",
       "    /* Redefinition of color scheme for dark theme */\n",
       "    --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n",
       "    --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, #111)));\n",
       "    --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n",
       "    --sklearn-color-icon: #878787;\n",
       "  }\n",
       "}\n",
       "\n",
       "#sk-container-id-1 {\n",
       "  color: var(--sklearn-color-text);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 pre {\n",
       "  padding: 0;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 input.sk-hidden--visually {\n",
       "  border: 0;\n",
       "  clip: rect(1px 1px 1px 1px);\n",
       "  clip: rect(1px, 1px, 1px, 1px);\n",
       "  height: 1px;\n",
       "  margin: -1px;\n",
       "  overflow: hidden;\n",
       "  padding: 0;\n",
       "  position: absolute;\n",
       "  width: 1px;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-dashed-wrapped {\n",
       "  border: 1px dashed var(--sklearn-color-line);\n",
       "  margin: 0 0.4em 0.5em 0.4em;\n",
       "  box-sizing: border-box;\n",
       "  padding-bottom: 0.4em;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-container {\n",
       "  /* jupyter's `normalize.less` sets `[hidden] { display: none; }`\n",
       "     but bootstrap.min.css set `[hidden] { display: none !important; }`\n",
       "     so we also need the `!important` here to be able to override the\n",
       "     default hidden behavior on the sphinx rendered scikit-learn.org.\n",
       "     See: https://github.com/scikit-learn/scikit-learn/issues/21755 */\n",
       "  display: inline-block !important;\n",
       "  position: relative;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-text-repr-fallback {\n",
       "  display: none;\n",
       "}\n",
       "\n",
       "div.sk-parallel-item,\n",
       "div.sk-serial,\n",
       "div.sk-item {\n",
       "  /* draw centered vertical line to link estimators */\n",
       "  background-image: linear-gradient(var(--sklearn-color-text-on-default-background), var(--sklearn-color-text-on-default-background));\n",
       "  background-size: 2px 100%;\n",
       "  background-repeat: no-repeat;\n",
       "  background-position: center center;\n",
       "}\n",
       "\n",
       "/* Parallel-specific style estimator block */\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item::after {\n",
       "  content: \"\";\n",
       "  width: 100%;\n",
       "  border-bottom: 2px solid var(--sklearn-color-text-on-default-background);\n",
       "  flex-grow: 1;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel {\n",
       "  display: flex;\n",
       "  align-items: stretch;\n",
       "  justify-content: center;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  position: relative;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item:first-child::after {\n",
       "  align-self: flex-end;\n",
       "  width: 50%;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item:last-child::after {\n",
       "  align-self: flex-start;\n",
       "  width: 50%;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-parallel-item:only-child::after {\n",
       "  width: 0;\n",
       "}\n",
       "\n",
       "/* Serial-specific style estimator block */\n",
       "\n",
       "#sk-container-id-1 div.sk-serial {\n",
       "  display: flex;\n",
       "  flex-direction: column;\n",
       "  align-items: center;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  padding-right: 1em;\n",
       "  padding-left: 1em;\n",
       "}\n",
       "\n",
       "\n",
       "/* Toggleable style: style used for estimator/Pipeline/ColumnTransformer box that is\n",
       "clickable and can be expanded/collapsed.\n",
       "- Pipeline and ColumnTransformer use this feature and define the default style\n",
       "- Estimators will overwrite some part of the style using the `sk-estimator` class\n",
       "*/\n",
       "\n",
       "/* Pipeline and ColumnTransformer style (default) */\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable {\n",
       "  /* Default theme specific background. It is overwritten whether we have a\n",
       "  specific estimator or a Pipeline/ColumnTransformer */\n",
       "  background-color: var(--sklearn-color-background);\n",
       "}\n",
       "\n",
       "/* Toggleable label */\n",
       "#sk-container-id-1 label.sk-toggleable__label {\n",
       "  cursor: pointer;\n",
       "  display: flex;\n",
       "  width: 100%;\n",
       "  margin-bottom: 0;\n",
       "  padding: 0.5em;\n",
       "  box-sizing: border-box;\n",
       "  text-align: center;\n",
       "  align-items: start;\n",
       "  justify-content: space-between;\n",
       "  gap: 0.5em;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 label.sk-toggleable__label .caption {\n",
       "  font-size: 0.6rem;\n",
       "  font-weight: lighter;\n",
       "  color: var(--sklearn-color-text-muted);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 label.sk-toggleable__label-arrow:before {\n",
       "  /* Arrow on the left of the label */\n",
       "  content: \"▸\";\n",
       "  float: left;\n",
       "  margin-right: 0.25em;\n",
       "  color: var(--sklearn-color-icon);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 label.sk-toggleable__label-arrow:hover:before {\n",
       "  color: var(--sklearn-color-text);\n",
       "}\n",
       "\n",
       "/* Toggleable content - dropdown */\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content {\n",
       "  display: none;\n",
       "  text-align: left;\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content.fitted {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content pre {\n",
       "  margin: 0.2em;\n",
       "  border-radius: 0.25em;\n",
       "  color: var(--sklearn-color-text);\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-toggleable__content.fitted pre {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 input.sk-toggleable__control:checked~div.sk-toggleable__content {\n",
       "  /* Expand drop-down */\n",
       "  display: block;\n",
       "  width: 100%;\n",
       "  overflow: visible;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {\n",
       "  content: \"▾\";\n",
       "}\n",
       "\n",
       "/* Pipeline/ColumnTransformer-specific style */\n",
       "\n",
       "#sk-container-id-1 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-label.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Estimator-specific style */\n",
       "\n",
       "/* Colorize estimator box */\n",
       "#sk-container-id-1 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-estimator.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-label label.sk-toggleable__label,\n",
       "#sk-container-id-1 div.sk-label label {\n",
       "  /* The background is the default theme color */\n",
       "  color: var(--sklearn-color-text-on-default-background);\n",
       "}\n",
       "\n",
       "/* On hover, darken the color of the background */\n",
       "#sk-container-id-1 div.sk-label:hover label.sk-toggleable__label {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "/* Label box, darken color on hover, fitted */\n",
       "#sk-container-id-1 div.sk-label.fitted:hover label.sk-toggleable__label.fitted {\n",
       "  color: var(--sklearn-color-text);\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Estimator label */\n",
       "\n",
       "#sk-container-id-1 div.sk-label label {\n",
       "  font-family: monospace;\n",
       "  font-weight: bold;\n",
       "  display: inline-block;\n",
       "  line-height: 1.2em;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-label-container {\n",
       "  text-align: center;\n",
       "}\n",
       "\n",
       "/* Estimator-specific */\n",
       "#sk-container-id-1 div.sk-estimator {\n",
       "  font-family: monospace;\n",
       "  border: 1px dotted var(--sklearn-color-border-box);\n",
       "  border-radius: 0.25em;\n",
       "  box-sizing: border-box;\n",
       "  margin-bottom: 0.5em;\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-0);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-estimator.fitted {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-0);\n",
       "}\n",
       "\n",
       "/* on hover */\n",
       "#sk-container-id-1 div.sk-estimator:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-2);\n",
       "}\n",
       "\n",
       "#sk-container-id-1 div.sk-estimator.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-2);\n",
       "}\n",
       "\n",
       "/* Specification for estimator info (e.g. \"i\" and \"?\") */\n",
       "\n",
       "/* Common style for \"i\" and \"?\" */\n",
       "\n",
       ".sk-estimator-doc-link,\n",
       "a:link.sk-estimator-doc-link,\n",
       "a:visited.sk-estimator-doc-link {\n",
       "  float: right;\n",
       "  font-size: smaller;\n",
       "  line-height: 1em;\n",
       "  font-family: monospace;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  border-radius: 1em;\n",
       "  height: 1em;\n",
       "  width: 1em;\n",
       "  text-decoration: none !important;\n",
       "  margin-left: 0.5em;\n",
       "  text-align: center;\n",
       "  /* unfitted */\n",
       "  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-unfitted-level-1);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link.fitted,\n",
       "a:link.sk-estimator-doc-link.fitted,\n",
       "a:visited.sk-estimator-doc-link.fitted {\n",
       "  /* fitted */\n",
       "  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-fitted-level-1);\n",
       "}\n",
       "\n",
       "/* On hover */\n",
       "div.sk-estimator:hover .sk-estimator-doc-link:hover,\n",
       ".sk-estimator-doc-link:hover,\n",
       "div.sk-label-container:hover .sk-estimator-doc-link:hover,\n",
       ".sk-estimator-doc-link:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "div.sk-estimator.fitted:hover .sk-estimator-doc-link.fitted:hover,\n",
       ".sk-estimator-doc-link.fitted:hover,\n",
       "div.sk-label-container:hover .sk-estimator-doc-link.fitted:hover,\n",
       ".sk-estimator-doc-link.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "/* Span, style for the box shown on hovering the info icon */\n",
       ".sk-estimator-doc-link span {\n",
       "  display: none;\n",
       "  z-index: 9999;\n",
       "  position: relative;\n",
       "  font-weight: normal;\n",
       "  right: .2ex;\n",
       "  padding: .5ex;\n",
       "  margin: .5ex;\n",
       "  width: min-content;\n",
       "  min-width: 20ex;\n",
       "  max-width: 50ex;\n",
       "  color: var(--sklearn-color-text);\n",
       "  box-shadow: 2pt 2pt 4pt #999;\n",
       "  /* unfitted */\n",
       "  background: var(--sklearn-color-unfitted-level-0);\n",
       "  border: .5pt solid var(--sklearn-color-unfitted-level-3);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link.fitted span {\n",
       "  /* fitted */\n",
       "  background: var(--sklearn-color-fitted-level-0);\n",
       "  border: var(--sklearn-color-fitted-level-3);\n",
       "}\n",
       "\n",
       ".sk-estimator-doc-link:hover span {\n",
       "  display: block;\n",
       "}\n",
       "\n",
       "/* \"?\"-specific style due to the `<a>` HTML tag */\n",
       "\n",
       "#sk-container-id-1 a.estimator_doc_link {\n",
       "  float: right;\n",
       "  font-size: 1rem;\n",
       "  line-height: 1em;\n",
       "  font-family: monospace;\n",
       "  background-color: var(--sklearn-color-background);\n",
       "  border-radius: 1rem;\n",
       "  height: 1rem;\n",
       "  width: 1rem;\n",
       "  text-decoration: none;\n",
       "  /* unfitted */\n",
       "  color: var(--sklearn-color-unfitted-level-1);\n",
       "  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 a.estimator_doc_link.fitted {\n",
       "  /* fitted */\n",
       "  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n",
       "  color: var(--sklearn-color-fitted-level-1);\n",
       "}\n",
       "\n",
       "/* On hover */\n",
       "#sk-container-id-1 a.estimator_doc_link:hover {\n",
       "  /* unfitted */\n",
       "  background-color: var(--sklearn-color-unfitted-level-3);\n",
       "  color: var(--sklearn-color-background);\n",
       "  text-decoration: none;\n",
       "}\n",
       "\n",
       "#sk-container-id-1 a.estimator_doc_link.fitted:hover {\n",
       "  /* fitted */\n",
       "  background-color: var(--sklearn-color-fitted-level-3);\n",
       "}\n",
       "\n",
       ".estimator-table summary {\n",
       "    padding: .5rem;\n",
       "    font-family: monospace;\n",
       "    cursor: pointer;\n",
       "}\n",
       "\n",
       ".estimator-table details[open] {\n",
       "    padding-left: 0.1rem;\n",
       "    padding-right: 0.1rem;\n",
       "    padding-bottom: 0.3rem;\n",
       "}\n",
       "\n",
       ".estimator-table .parameters-table {\n",
       "    margin-left: auto !important;\n",
       "    margin-right: auto !important;\n",
       "}\n",
       "\n",
       ".estimator-table .parameters-table tr:nth-child(odd) {\n",
       "    background-color: #fff;\n",
       "}\n",
       "\n",
       ".estimator-table .parameters-table tr:nth-child(even) {\n",
       "    background-color: #f6f6f6;\n",
       "}\n",
       "\n",
       ".estimator-table .parameters-table tr:hover {\n",
       "    background-color: #e0e0e0;\n",
       "}\n",
       "\n",
       ".estimator-table table td {\n",
       "    border: 1px solid rgba(106, 105, 104, 0.232);\n",
       "}\n",
       "\n",
       ".user-set td {\n",
       "    color:rgb(255, 94, 0);\n",
       "    text-align: left;\n",
       "}\n",
       "\n",
       ".user-set td.value pre {\n",
       "    color:rgb(255, 94, 0) !important;\n",
       "    background-color: transparent !important;\n",
       "}\n",
       "\n",
       ".default td {\n",
       "    color: black;\n",
       "    text-align: left;\n",
       "}\n",
       "\n",
       ".user-set td i,\n",
       ".default td i {\n",
       "    color: black;\n",
       "}\n",
       "\n",
       ".copy-paste-icon {\n",
       "    background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tIUZvbnQgQXdlc29tZSBGcmVlIDYuNy4yIGJ5IEBmb250YXdlc29tZSAtIGh0dHBzOi8vZm9udGF3ZXNvbWUuY29tIExpY2Vuc2UgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbS9saWNlbnNlL2ZyZWUgQ29weXJpZ2h0IDIwMjUgRm9udGljb25zLCBJbmMuLS0+PHBhdGggZD0iTTIwOCAwTDMzMi4xIDBjMTIuNyAwIDI0LjkgNS4xIDMzLjkgMTQuMWw2Ny45IDY3LjljOSA5IDE0LjEgMjEuMiAxNC4xIDMzLjlMNDQ4IDMzNmMwIDI2LjUtMjEuNSA0OC00OCA0OGwtMTkyIDBjLTI2LjUgMC00OC0yMS41LTQ4LTQ4bDAtMjg4YzAtMjYuNSAyMS41LTQ4IDQ4LTQ4ek00OCAxMjhsODAgMCAwIDY0LTY0IDAgMCAyNTYgMTkyIDAgMC0zMiA2NCAwIDAgNDhjMCAyNi41LTIxLjUgNDgtNDggNDhMNDggNTEyYy0yNi41IDAtNDgtMjEuNS00OC00OEwwIDE3NmMwLTI2LjUgMjEuNS00OCA0OC00OHoiLz48L3N2Zz4=);\n",
       "    background-repeat: no-repeat;\n",
       "    background-size: 14px 14px;\n",
       "    background-position: 0;\n",
       "    display: inline-block;\n",
       "    width: 14px;\n",
       "    height: 14px;\n",
       "    cursor: pointer;\n",
       "}\n",
       "</style><body><div id=\"sk-container-id-1\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>LinearRegression()</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item\"><div class=\"sk-estimator fitted sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-1\" type=\"checkbox\" checked><label for=\"sk-estimator-id-1\" class=\"sk-toggleable__label fitted sk-toggleable__label-arrow\"><div><div>LinearRegression</div></div><div><a class=\"sk-estimator-doc-link fitted\" rel=\"noreferrer\" target=\"_blank\" href=\"https://scikit-learn.org/1.7/modules/generated/sklearn.linear_model.LinearRegression.html\">?<span>Documentation for LinearRegression</span></a><span class=\"sk-estimator-doc-link fitted\">i<span>Fitted</span></span></div></label><div class=\"sk-toggleable__content fitted\" data-param-prefix=\"\">\n",
       "        <div class=\"estimator-table\">\n",
       "            <details>\n",
       "                <summary>Parameters</summary>\n",
       "                <table class=\"parameters-table\">\n",
       "                  <tbody>\n",
       "                    \n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('fit_intercept',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">fit_intercept&nbsp;</td>\n",
       "            <td class=\"value\">True</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('copy_X',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">copy_X&nbsp;</td>\n",
       "            <td class=\"value\">True</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('tol',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">tol&nbsp;</td>\n",
       "            <td class=\"value\">1e-06</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('n_jobs',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">n_jobs&nbsp;</td>\n",
       "            <td class=\"value\">None</td>\n",
       "        </tr>\n",
       "    \n",
       "\n",
       "        <tr class=\"default\">\n",
       "            <td><i class=\"copy-paste-icon\"\n",
       "                 onclick=\"copyToClipboard('positive',\n",
       "                          this.parentElement.nextElementSibling)\"\n",
       "            ></i></td>\n",
       "            <td class=\"param\">positive&nbsp;</td>\n",
       "            <td class=\"value\">False</td>\n",
       "        </tr>\n",
       "    \n",
       "                  </tbody>\n",
       "                </table>\n",
       "            </details>\n",
       "        </div>\n",
       "    </div></div></div></div></div><script>function copyToClipboard(text, element) {\n",
       "    // Get the parameter prefix from the closest toggleable content\n",
       "    const toggleableContent = element.closest('.sk-toggleable__content');\n",
       "    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';\n",
       "    const fullParamName = paramPrefix ? `${paramPrefix}${text}` : text;\n",
       "\n",
       "    const originalStyle = element.style;\n",
       "    const computedStyle = window.getComputedStyle(element);\n",
       "    const originalWidth = computedStyle.width;\n",
       "    const originalHTML = element.innerHTML.replace('Copied!', '');\n",
       "\n",
       "    navigator.clipboard.writeText(fullParamName)\n",
       "        .then(() => {\n",
       "            element.style.width = originalWidth;\n",
       "            element.style.color = 'green';\n",
       "            element.innerHTML = \"Copied!\";\n",
       "\n",
       "            setTimeout(() => {\n",
       "                element.innerHTML = originalHTML;\n",
       "                element.style = originalStyle;\n",
       "            }, 2000);\n",
       "        })\n",
       "        .catch(err => {\n",
       "            console.error('Failed to copy:', err);\n",
       "            element.style.color = 'red';\n",
       "            element.innerHTML = \"Failed!\";\n",
       "            setTimeout(() => {\n",
       "                element.innerHTML = originalHTML;\n",
       "                element.style = originalStyle;\n",
       "            }, 2000);\n",
       "        });\n",
       "    return false;\n",
       "}\n",
       "\n",
       "document.querySelectorAll('.fa-regular.fa-copy').forEach(function(element) {\n",
       "    const toggleableContent = element.closest('.sk-toggleable__content');\n",
       "    const paramPrefix = toggleableContent ? toggleableContent.dataset.paramPrefix : '';\n",
       "    const paramName = element.parentElement.nextElementSibling.textContent.trim();\n",
       "    const fullParamName = paramPrefix ? `${paramPrefix}${paramName}` : paramName;\n",
       "\n",
       "    element.setAttribute('title', fullParamName);\n",
       "});\n",
       "</script></body>"
      ],
      "text/plain": [
       "LinearRegression()"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.linear_model import LinearRegression\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X, y, test_size=0.2, random_state=42\n",
    ")\n",
    "\n",
    "model = LinearRegression()\n",
    "model.fit(X_train, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "fda816d3-0786-42c0-bda9-f9fd4722fd9c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "R2 Score: 0.899438024100912\n"
     ]
    }
   ],
   "source": [
    "from sklearn.metrics import r2_score\n",
    "\n",
    "y_pred = model.predict(X_test)\n",
    "print(\"R2 Score:\", r2_score(y_test, y_pred))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "d9266db3-cb3a-40c4-a403-d37a1e39c9a3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Predicted Sales: 20.61\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Lenovo\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names\n",
      "  warnings.warn(\n"
     ]
    }
   ],
   "source": [
    "sample = [[230.1, 37.8, 69.2]]\n",
    "\n",
    "print(\"Predicted Sales:\", round(model.predict(sample)[0], 2))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8e35e9e0-2af7-446c-9cf4-cb17fbcd4499",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
